<?php

namespace tests;
use PasswordValidator;

class PasswordValidatorTest extends \PHPUnit\Framework\TestCase
{

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }




    /**
     * @test
     */
    public function checkPasswordWithLessThan8CharacterFail()
    {
        $password = "azertyu";
    }



    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

}